name: Release
on:
  push:
    tags:
      - '*'

jobs:
  zip_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update module.json version and download URL
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          jq --arg VERSION "$VERSION" \
             --arg DOWNLOAD_URL "https://github.com/${{ github.repository }}/releases/download/$VERSION/release.zip" \
             '.version = $VERSION | .download = $DOWNLOAD_URL' module.json > temp.json && mv temp.json module.json

      - name: Zip module files
        run: |
          sudo apt-get install zip &&
          zip -r release.zip lang/ module/ presets/ styles/ templates/ textures/ license.md module.json readme.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            module.json
            release.zip

      - name: Publish to Foundry Package Registry
        if: ${{ !contains(github.ref, 'beta') }}
        run: |
          VERSION_TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          VERSION=$(jq -r '.version' module.json)
          MINIMUM=$(jq -r '.compatibility.minimum' module.json)
          VERIFIED=$(jq -r '.compatibility.verified' module.json)
          MAXIMUM=$(jq -r '.compatibility.maximum' module.json)
          curl -X POST https://api.foundryvtt.com/_api/packages/release_version/ \
               -H 'Content-Type: application/json' \
               -H 'Authorization: ${{ secrets.FOUNDRY_AUTH_TOKEN }}' \
               -d '{
                     "id": "terrain-height-tools",
                     "release": {
                       "version": "'"$VERSION"'",
                       "manifest": "https://github.com/${{ github.repository }}/releases/download/'"$VERSION_TAG"'/module.json",
                       "notes": "https://github.com/${{ github.repository }}/releases/tag/'"$VERSION_TAG"'",
                       "compatibility": {
                         "minimum": "'"$MINIMUM"'",
                         "verified": "'"$VERIFIED"'",
                         "maximum": "'"$MAXIMUM"'"
                       }
                     }
                   }'
